id: I9A57AE3D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:48:16+00:00'
last_modified: '2022-06-07T18:41:08.306321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24672
  title: གསོ་རིག་འབུམ་བཞི
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2B99:
      image_group_id: I4703
      title: ''
      total_pages: 333
      order: 1
      base_file: 2B99.txt
    48C2:
      image_group_id: I4704
      title: ''
      total_pages: 640
      order: 2
      base_file: 48C2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
